# Generated by Django 2.1.7 on 2019-04-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('image', models.ImageField(upload_to='img')),
                ('introduce', models.CharField(default=None, max_length=150)),
            ],
            options={
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorials.Category'),
        ),
    ]
