# Generated by Django 2.1.7 on 2019-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190425_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '课程分类表'},
        ),
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name_plural': '课程清单'},
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='introduce',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='description',
            field=models.CharField(default=None, max_length=150, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='缩略图'),
        ),
    ]
