# Generated by Django 2.1.7 on 2019-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20190425_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='缩略图'),
        ),
    ]
