# Generated by Django 2.1.7 on 2019-04-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20190426_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('Please Edtor your content', models.TextField(verbose_name='Detail')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorials.Tutorials')),
            ],
            options={
                'verbose_name': 'Wenzhan',
                'verbose_name_plural': 'Wenzhan',
            },
        ),
    ]
