# Generated by Django 2.1.7 on 2019-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='Please Edtor your content',
        ),
        migrations.AddField(
            model_name='articles',
            name='article',
            field=models.TextField(default='Please Input information'),
        ),
    ]
