# Generated by Django 2.1.7 on 2019-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20190428_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('操作系统', 'OS')], max_length=20, verbose_name='分类名'),
        ),
    ]
