# Generated by Django 2.1.7 on 2019-04-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20190428_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='陈煜', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('os', '操作系统'), ('python', 'Python'), ('java', 'Java'), ('js', 'Javascript'), ('c', 'C'), ('cplus', 'C++')], max_length=20, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorials.Category', verbose_name='分类名'),
        ),
    ]
